geshifilter.settings:
  type: config_object
  label: "Setting for geshifilter module"
  mapping:
    langcode:
      type: string
      label: 'Default language'
    tags:
      type: string
      label: 'HTML tags for geshifilter blocks, like code, blockcode'
    use_format_specific_options:
      type: boolean
      label: "When use options for each filter or use the same for all"
    default_highlighting:
      type: string
    default_line_numbering:
      type: integer
    use_highlight_string_for_php:
      type: boolean
    decode_entities:
      type: boolean
    enable_keyword_urls:
      type: boolean
    css_mode:
      type: integer
    code_container:
      type: string
    geshi_dir:
      type: string
    tags:
      type: string
    tag_styles:
      type: sequence
      sequence:
        - type: integer
    tab_width:
      type: integer
    language:
      type: sequence
      sequence:
        - type: mapping
          mapping:
            enabled:
              type: boolean
            tags:
              type: string

filter_settings.filter_geshifilter:
  type: filter
  label: 'Filter HTML'
  mapping:
    general_tags:
      type: mapping
      mapping:
        tags:
          type: string
          label: 'HTML tags for geshifilter blocks, like code, blockcode.'
        tag_styles:
          type: sequence
          sequence:
            - type: integer
        decode_entities:
          type: boolean
          label: "When decode html entities before processing by geshi."
    per_language_settings:
      type: sequence
